name: Java CI & Javadoc

on:
  push:
    branches: [ "*" ]

permissions:
  contents: write # Autorise le bot à pousser la documentation sur le repo

jobs:
  build-and-document:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Configuration de Java 21 (Temurin)
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Compilation et Vérification (Linter par défaut Maven)
      # Vérifie que le code compile, exécute les tests, et valide le format
      run: mvn -B clean verify

    - name: Génération de la Javadoc
      # Crée le dossier /target/site/apidocs
      run: mvn -B javadoc:javadoc

    - name: Déploiement de la Javadoc sur GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/apidocs
        publish_branch: gh-pages
        commit_message: "docs: Mise à jour automatique de la Javadoc"
